#!/bin/bash

cp schema.upstream.yaml schema.yaml
# The API actually returns 201 but spec only allows 200.
yq -i '.paths./v2/businesses.post.responses.201 = .paths./v2/businesses.post.responses.200' schema.yaml
# The API seems to return values not included in the enum.
yq -i 'del(.components.schemas.GetChartOfAccountsDataV2.properties.subType.enum)' schema.yaml
# openapi-python-client can't handle multiple content types with the same schema type.
yq -i 'del(.paths./v2/accounting/attachments.post.requestBody.content.application/json)' schema.yaml
# push /data/sync doesn't return most of the required fields (at least on sandbox)
yq -i 'del(.components.schemas.DataSyncResponseV2Dto.required)' schema.yaml
# API actually wants date, not date-time ("postedDate must be formatted as yyyy-mm-dd")
yq -i '.components.schemas.PushBankTransactionV2.properties.postedDate.format = "date"' schema.yaml
# BusinessInfoDataV2.businessType isn't always present and we don't care about the other required field.
yq -i 'del(.components.schemas.BusinessInfoDataV2.required)' schema.yaml
