#!/bin/bash
openapi-python-client generate --config openapi-python-client.yaml --path schema.yaml --overwrite --custom-template-path=templates
rg --files-with-matches --type=py '\bMapping\b' railz-api-client | xargs sed -r -i '0,/(.*\bimport\b.*)/s//from typing import Mapping\n\1/'
ruff check --fix .
ruff format .
if [[ -z "$(git status --porcelain railz-api-client)" ]]; then
  echo "Already up to date"
  exit
fi
prev_ver="$(grep package_version_override openapi-python-client.yaml | sed 's/.*: //')"
prev_ver_num="$(echo "${prev_ver}" | sed -r 's/.*[^0-9]//')"
new_ver_num="$(( ${prev_ver_num} + 1 ))"
new_ver="$(echo "${prev_ver}" | sed -r 's/[0-9]+$/'"${new_ver_num}/" )"
sed -i "s/${prev_ver}/${new_ver}/" openapi-python-client.yaml railz-api-client/pyproject.toml
echo "Bumped version from ${prev_ver} to ${new_ver}"
