#!/bin/bash

if ! command -v yq 2>&1 >/dev/null; then
  echo "Please install yq from https://github.com/mikefarah/yq/#install"
  exit 1
fi

curl https://api.railz.ai/swagger/v2 | yq -Poy > schema.yaml
# The API actually returns 201 but spec only allows 200.
yq -i '.paths./v2/businesses.post.responses.201 = .paths./v2/businesses.post.responses.200' schema.yaml
# The API seems to return values not included in the enum.
yq -i 'del(.components.schemas.GetChartOfAccountsDataV2.properties.subType.enum)' schema.yaml
